type ThemeIcons = "LightIcon" | "DarkIcon" | "SystemThemeIcon";
type Icons = 
    "AccountIcon" |
    "AppearanceIcon" |
    "ArrowIcon" |
    "AutoReplyBotIcon" |
    "BlogIcon" |
    "CalendarIcon" |
    "CancelIcon" |
    "CheckIcon" |
    "CopyIcon" |
    "DangerIcon" |
    "DangerFillIcon" |
    "DarkIcon" |
    "DeprecatedIcon" |
    "DesktopIcon" |
    "DevIcon" |
    "DonateIcon" |
    "DownloadIcon" |
    "DragFileIcon" |
    "EditIcon" |
    "EnglishIcon" |
    "EspanolIcon" |
    "ExperimentalIcon" |
    "FileIcon" |
    "FolderIcon" |
    "HamburgerButtonIcon" |
    "HomeIcon" |
    "InformationIcon" |
    "InformationFillIcon" |
    "JapaneseIcon" |
    "KoreanIcon" |
    "LaptopIcon" |
    "LightIcon" |
    "LinkIcon" |
    "MessengerbotRIcon" |
    "MobileIcon" |
    "NolboIcon" |
    "NonStandardIcon" |
    "PartialIcon" |
    "PidocIcon" |
    "PostIcon" |
    "ReactIcon" |
    "SearchIcon" |
    "SettingsIcon" |
    "SpeedIcon" |
    "StandardIcon" |
    "StarLightIcon" |
    "SuccessIcon" |
    "SuccessFillIcon" |
    "SystemThemeIcon" |
    "TabletIcon" |
    "TypescriptIcon" |
    "UploadIcon" |
    "WarningIcon" |
    "WarningFillIcon";